### PR TITLE
Define default currency per country

### PR DESCRIPTION
**Pull request by willemwollebrants**
This pr addresses the issue raised in #52 

Some countries have multiple currencies, but only one "default" currency. The other currencies are used mainly by banks and funds. 

This pr adds a new (optional) element to the .json-files: 'default_currency'. This holds the ISO 4217 code of the default currency. The default_currency has been set for all 4 countries identified by @khsing

A new method Country::getDefaultCurrency is also available. This will return either the default_currency if it's defined for the country, or use Country::getCurrency as a fallback.

### CODE REVIEW

**Comment by andrew-s** [comment]
I'd like to see this PR merged in, this package is fantastically useful *however* USN was definitely an unexpected currency to have seen when requesting currency on the US.

**Comment by helmuthva** [comment]
getCurrency returning USN for US and CHE for CH is not useful - would be great to have this PR merged.

**Comment by fede91it** [comment]
What about merging this?

**Comment by fede91it** [comment]
Nothing?

**Comment by Omranic** [comment]
This is now fixed fundamentaly for all countries in https://github.com/rinvex/countries/commit/1cf372b29bc0c17eeaf08e40a7cd98b729aae296, here's what's been done:

Update country currencies to include only the official currency (fix #52 #55 #72)
- Removed fund, complementary and secondary currencies as it's not relevant to the countries package, and caused confusion before
- This change affected 15 countries: Bolivia, Bhutan, Belarus, Switzerland, Chile, Cuba, Western Sahara, Haiti, British Indian Ocean Territory, Lesotho, Namibia, Panama, El Salvador, United States, Uruguay

**Pull request closed without merging**
